export enum ETags {
  KHO = "เกาะ",
  TALE = "ทะเล",
  VIEWPOINT = "จุดชมวิว",
  NATURAL = "ธรรมชาติ",
  CAFE = "คาเฟ่",
  COFFEESHOP = "ร้านกาแฟ",
  PHOTOSPOT = "จุดถ่ายภาพ",
  NEARMETRO = "เที่ยวใกล้กรุง",
  NICEPHOTO = "ถ่ายรูปสวย",
  VILLAGE = "หมู่บ้าน",
  MOUNTAIN = "ภูเขา",
  PILOG = "บ้านอีต่องเหมืองปิล็อก",
  ABORAD = "ต่างประเทศ",
  TAIWAN = "ไต้หวัน",
  JAPAN = "ญี่ปุ่น",
  FRANCE = "ฝรั่งเศส",
  SNOW = "หิมะ",
  FINLAND = "ฟินแลนด์",
  KANCHANABURI = "กาญจนบุรี",
  CHONBURI = "ชลบุรี",
  BANGKOK = "กรุงเทพมหานคร",
  TRAD = "ตราด",
  CHIANGMAI = "เชียงใหม่",
  SATUL = "สตูล",
}
